### ISSUE TITLE
missing repo config for TLA

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/DOGlib#11]
Handles like

http://hdl.handle.net/1839/00-0000-0000-0018-A640-9@view
http://hdl.handle.net/1839/00-0000-0000-0018-A640-9

are not recognized. They rewrite to URLs like

https://archive.mpi.nl/objects/tla:1839_00_0000_0000_0018_A640_9/datastreams/CMD/content?asOfDateTime=2018-03-02T11:00:00.000Z

and return the correct mimetype application/x-cmdi+xml

**Comment by MichalGawor** [comment]
HDL's resolve to URL different from the one in the example:
https://archive.mpi.nl/tla/islandora/object/tla:1839_00_0000_0000_0018_A640_9?asOfDateTime=2018-03-02T11:00:00.000Z
URL above does not support content negotiation, while the HDL itself does. Example URL also support content negotiation. 
In order to support both URL's  by parsing record ID from both URL's and obtaining CMDI via content negotiation through:
https://archive.mpi.nl/objects/tla:1839_$record_id/datastreams/CMD/content
